language: cpp

compiler:
- gcc
- clang

env:
- CONFIGURE_ARGS="--enable-release --disable-debug --disable-editor --without-opengl"
- CONFIGURE_ARGS="--enable-release --disable-debug --disable-editor --with-opengl"
- CONFIGURE_ARGS="--enable-release --disable-debug --enable-editor --without-opengl"
- CONFIGURE_ARGS="--enable-release --disable-debug --enable-editor --with-opengl"
- CONFIGURE_ARGS="--disable-release --enable-debug --disable-editor --without-opengl"
- CONFIGURE_ARGS="--disable-release --enable-debug --disable-editor --with-opengl"
- CONFIGURE_ARGS="--disable-release --enable-debug --enable-editor --without-opengl"
- CONFIGURE_ARGS="--disable-release --enable-debug --enable-editor --with-opengl"

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libphysfs-dev libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev

script: ./autogen.sh && ./configure $CONFIGURE_ARGS && make
