language: c

compiler:
# - gcc
  - clang
  - x86_64-w64-mingw32-gcc

env:
  - CONFIGURE_ARGS=" --enable-release --disable-debug --disable-editor --with-opengl"
  - CONFIGURE_ARGS=" --enable-release --disable-debug  --enable-editor --with-opengl"
  - CONFIGURE_ARGS="--disable-release  --enable-debug --disable-editor --with-opengl"
  - CONFIGURE_ARGS="--disable-release  --enable-debug  --enable-editor --with-opengl"

before_install:
  - sudo apt-get update -qq

  - if [ "$CC" = "gcc" ]; then sudo apt-get install -y libphysfs-dev libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev; fi

  - if [ "$CC" = "clang" ]; then sudo apt-get install -y libphysfs-dev libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev; fi

  - if [ "$CC" = "x86_64-w64-mingw32-gcc" ]; then sudo apt-get remove -qq -y mingw32; fi
  - if [ "$CC" = "x86_64-w64-mingw32-gcc" ]; then sudo apt-get install -y mingw-w64; fi
  - if [ "$CC" = "x86_64-w64-mingw32-gcc" ]; then export CONFIGURE_ARGS="$CONFIGURE_ARGS --host x86_64-w64-mingw32 --disable-network --with-sdl-prefix=`pwd`/mingw CPPFLAGS=-Imingw/include LDFLAGS=-Lmingw/lib PKG_CONFIG_LIBDIR=`pwd`/mingw/lib/pkgconfig"; fi

script:
  - ./autogen.sh
  - ./configure $CONFIGURE_ARGS
  - make
