language: cpp

compiler:
- gcc
- clang

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libphysfs-dev libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev

script: ./autogen.sh && ./configure --with-opengl && make
