language: c

compiler:
# - gcc
  - clang
  - i586-mingw32msvc-gcc
# - i686-w64-mingw32-gcc
  - x86_64-w64-mingw32-gcc

env:
  - CONFLAGS=" --enable-release --disable-debug  --enable-editor --with-opengl"
  - CONFLAGS="--disable-release  --enable-debug  --enable-editor --with-opengl"

before_install:
  - sudo apt-get update -qq

# native compilation
  - case $CC in gcc|clang) sudo apt-get install -y libphysfs-dev libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev; esac

  - case $CC in *-w64-mingw32-*) sudo apt-get remove -qq -y mingw32; esac
  - case $CC in *-w64-mingw32-*) sudo apt-get install -y mingw-w64; esac

  - case $CC in *-*-gcc) export CONFLAGS="$CONFLAGS --host $(basename $CC -gcc)"; esac

  - case $CC in i?86-*mingw32*-*) export CONFLAGS="$CONFLAGS --with-sdl-prefix=`pwd`/arch/win32 CPPFLAGS=-Iarch/win32/include LDFLAGS=-Larch/win32/lib PKG_CONFIG_LIBDIR=`pwd`/arch/win32/lib/pkgconfig"; esac

  - case $CC in x86_64-*mingw32*-*) export CONFLAGS="$CONFLAGS --with-sdl-prefix=`pwd`/arch/win64 CPPFLAGS=-Iarch/win64/include LDFLAGS=-Larch/win64/lib PKG_CONFIG_LIBDIR=`pwd`/arch/win64/lib/pkgconfig"; esac

  - echo $CONFLAGS

script:
  - ./autogen.sh
  - ./configure $CONFLAGS
  - make

deploy:
  provider: releases
  api_key:
    secure: Az9+gNmtIdRVTIMixHmLAOgcmAd94ECemfNxVPyG8v/NXPKjV3uTJu0im3A1p2rlpjwwIpIcC92v9lCxcxO4MMPzP05Q15WILXMlUoTt40c3gmFRdhwsfmxCLk1eH/wXeUhTGahgDb/Fq3OttNQiGOErAT4ew2+8Kx6skUmp1r0=
  file:
    - miner-gl.exe
    - d2x-gl.exe
    - miner-sdl.exe
    - d2x-sdl.exe
  skip-cleanup: true
  on:
    repo: btb/d2x
    tags: true
    condition: "$CC = x86_64-w64-mingw32-gcc"
