name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        editor: [enable, disable]
        macdata: [enable, disable]
        debug: [enable, disable]
        release: [enable, disable]
        linuxjoy: [enable, disable]
        fastfileio: [enable, disable]
        kalinix: [enable, disable]
        assembler: [enable, disable]
        opengl: [with, without]
        svga: [with, without] 

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install -y libphysfs-dev libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure \
        --${{ matrix.editor }}-editor \
        --${{ matrix.macdata }}-macdata \
        --${{ matrix.debug }}-debug \
        --${{ matrix.release }}-release \
        --${{ matrix.release }}-linuxjoy \
        --${{ matrix.release }}-fastfileio \
        --${{ matrix.release }}-kalinix \
        --${{ matrix.release }}-assembler \
        --${{ matrix.release }}-opengl \
        --${{ matrix.release }}-svga

    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
