name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install -y libphysfs-dev libsdl1.2-dev libsdl-mixer1.2-dev libsdl-image1.2-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --enable-release --disable-debug  --enable-editor --with-opengl
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
