# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the miner branch
  push:
    branches: [ miner ]
  pull_request:
    branches: [ miner ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: download watcom
        run: Invoke-WebRequest -Uri "https://sourceforge.net/projects/openwatcom/files/open-watcom-1.9/open-watcom-c-win32-1.9.exe/download" -OutFile OW19.exe
        shell: powershell

      - name: install watcom
        run: .\OW19.exe -i
        shell: cmd
      
      - name: set env
        run: c:\watcom\owsetenv.bat
        shell: cmd
      
      - name: show env
        run: set
        shell: cmd

      - name: show env ps
        run: dir "env:"
        shell: powershell


